### ISSUE TITLE
Fix cypress test failure in apim-apps repo

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#1047]
### Description

Need to fix the login related test failure in apim-apps repo

### Affected Component

APIM

**Comment by tharikaGitHub** [comment]
**Update** : There are 15 cypress test failures. The test failures related to publisher login was due to a missing variable name. The test should be fixed.

**Comment by imsuneth** [comment]
Some tests in following test files are failing:

devportal/000-general/03-sef-signup.spec.js - Fixed
Login failed message has changed - fixed

publisher/001-api-create/01-login-logout-from-publisher-as-super-tenant-user.spec.js - Fixed
Login page element name “usernameUserInput” has changed to “username”

devportal/001-applications/05-test-application-sharing.spec.js - Not yet fixed
“org” property has removed from the form when creating a user
“group id” property has removed from the form when creating an application

Therefore, the application created by userA is not visible to userB hence failing the test. @tharikaGitHub How can we proceed with this?

**Comment by tharikaGitHub** [comment]
The application sharing issue is due to https://github.com/wso2/api-manager/issues/1071. Once this is fixed, it should work.

**Comment by tharikaGitHub** [comment]
@imsuneth The issue https://github.com/wso2/api-manager/issues/1071 is resolved. We need to modify the tests accordingly.

**Comment by imsuneth** [comment]
A step to check the "Supported by Default" for local claim http://wso2.org/claims/organization in carbon is added with the above fix.
